version: "3"
services:
  web:
    build: ./.docker/nginx
    container_name: web
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/loganalizer
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./test/site.conf:/etc/nginx/conf.d/test.conf
    links:
      - php-fpm
      - mysql
    depends_on:
      - php-fpm
    extra_hosts:
      - "loganalizer.test:172.21.0.5"
      - "php-docker.test:172.21.0.5"
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    restart: always
  mysql:
    # build: ./docker/mysql
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "loganalaizer"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "homestead"
      # You can use whatever password you like
      MYSQL_PASSWORD: "secret"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - loganalaizer:/var/lib/mysql
  php-fpm:
    build: ./.docker/php
    container_name: php-fpm
    image: php:7-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/loganalizer
    depends_on:
      - mysql
    extra_hosts:
      - "loganalizer.test:172.21.0.5"
      - "php-docker.test:172.21.0.5"
    tty: true
volumes:
  loganalaizer:
